<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Basic_Dev_Onboarding</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>58aee375-e41a-4608-8a20-24c780c086b0</testSuiteGuid>
   <testCaseLink>
      <guid>a24cc61c-4a8c-45fc-be06-867ed52ced56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API Test Cases/Basic_Quickstart_Test_Case/Basic_Onboarding</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ab6d80b3-7fbb-46f7-8b3c-5bc83b5157af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API Test Cases/Basic_Quickstart_Test_Case/Dev Onboarding</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94fe0f4b-e8c1-4492-a899-fdae7b408c5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acc61cec-ab3b-40d2-8aef-c9e9123e3142</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d183d80-cb38-4486-8781-feb18aacaa2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7be1cc5a-9781-4ba6-9e8d-7aeeb9091292</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27f4fe09-fed7-461c-b191-0ee4823f1fe9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>250ebf5c-69df-4b94-b3fe-83b31dacc1e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad98a768-cc3f-4102-b2fd-66fb2a4524f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b201b7db-c677-45cd-9aab-9522460bc3fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20f10e00-a070-45ad-8c3a-a392ee94812c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
