<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>transaction</name>
   <tag></tag>
   <elementGuidId>5262e4a3-c746-4c8b-ac8c-ef7195b159fd</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic NmI4MGEzODMtNTZhYi00ZjRkLWFkYzItYTk1ZDFiNzVlODgxOjZlMGUzMTQ3LTljZWEtNDIwNS1hOWUzLTUyMDBiZGZjMTM4Zg==</value>
   </httpHeaderProperties>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>https://${url}/transactions?count=${count}&amp;start_index=${start_index}&amp;sort_by=${sort_by}&amp;state=${state}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.url</defaultValue>
      <description></description>
      <id>4271d344-f2b0-4022-b4b4-c5b87e892e72</id>
      <masked>false</masked>
      <name>url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.count</defaultValue>
      <description></description>
      <id>be091c4e-d8a9-4d76-a8f2-99c32d80d5c6</id>
      <masked>false</masked>
      <name>count</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.start_index</defaultValue>
      <description></description>
      <id>0ddb7d3e-53b9-4942-92ce-6a77d9eaf188</id>
      <masked>false</masked>
      <name>start_index</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.sort_by</defaultValue>
      <description></description>
      <id>eb6dd6d0-12a0-456d-820a-5a2b5d2520ee</id>
      <masked>false</masked>
      <name>sort_by</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.state</defaultValue>
      <description></description>
      <id>de0b5829-8c3f-4726-b291-f72baa9c38e4</id>
      <masked>false</masked>
      <name>state</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
