<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>create user invalid ssn</name>
   <tag></tag>
   <elementGuidId>6408c1f8-8880-413e-961a-f63d98dc41e7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n  \&quot;active\&quot;: true,\n  \&quot;notes\&quot;: \&quot;${notes}\&quot;,\n  \&quot;password\&quot;: \&quot;${password}\&quot;,\n  \&quot;phone\&quot;: \&quot;${phone}\&quot;,\n  \&quot;identifications\&quot;: [\n    {\n      \&quot;expiration_date\&quot;: \&quot;${expiration_date}\&quot;\n    }\n  ],\n  \&quot;gender\&quot;: \&quot;${gender}\&quot;,\n  \&quot;first_name\&quot;: \&quot;${first_name}\&quot;,\n  \&quot;middle_name\&quot;: \&quot;${middle_name}\&quot;,\n  \&quot;last_name\&quot;: \&quot;${last_name}\&quot;,\n  \&quot;email\&quot;: \&quot;${email}\&quot;,\n  \&quot;address1\&quot;: \&quot;${address1}\&quot;,\n  \&quot;city\&quot;: \&quot;${city}\&quot;,\n  \&quot;state\&quot;: \&quot;${state}\&quot;,\n  \&quot;country\&quot;: \&quot;${country}\&quot;,\n  \&quot;birth_date\&quot;: \&quot;${birth_date}\&quot;,\n  \&quot;corporate_card_holder\&quot;: false,\n  \&quot;ssn\&quot;: \&quot;${ssn}\&quot;,\n  \&quot;id_card_number\&quot;: \&quot;${id_card_number}\&quot;,\n  \&quot;id_card_expiration_date\&quot;: \&quot;${id_card_expiration_date}\&quot;,\n  \&quot;nationality\&quot;: \&quot;${nationality}\&quot;,\n  \&quot;company\&quot;: \&quot;${company}\&quot;,\n  \&quot;uses_parent_account\&quot;: false,\n  \&quot;postal_code\&quot;: \&quot;${postal_code}\&quot;\n}&quot;,
  &quot;contentType&quot;: &quot;text/plain&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic NmI4MGEzODMtNTZhYi00ZjRkLWFkYzItYTk1ZDFiNzVlODgxOjZlMGUzMTQ3LTljZWEtNDIwNS1hOWUzLTUyMDBiZGZjMTM4Zg==</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://${url}/users</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.url</defaultValue>
      <description></description>
      <id>80990d73-a8ac-404e-96e6-1aa2a5e5368f</id>
      <masked>false</masked>
      <name>url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.notes</defaultValue>
      <description></description>
      <id>723ea06c-394a-4c30-b53b-52bbbe47fae4</id>
      <masked>false</masked>
      <name>notes</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.password</defaultValue>
      <description></description>
      <id>b7de95e7-4751-4e89-b8e2-e7a30c63ca23</id>
      <masked>false</masked>
      <name>password</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.phone</defaultValue>
      <description></description>
      <id>9faed982-f8cf-425c-8c90-4da73ea51a10</id>
      <masked>false</masked>
      <name>phone</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.expiration_date</defaultValue>
      <description></description>
      <id>d96d5f51-6c3f-46f1-8255-3635d7d81332</id>
      <masked>false</masked>
      <name>expiration_date</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.gender</defaultValue>
      <description></description>
      <id>0903d7de-260b-4429-aaeb-ef1a5bc8cfc1</id>
      <masked>false</masked>
      <name>gender</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.first_name</defaultValue>
      <description></description>
      <id>e9ba0e9d-7d39-4992-91b6-8a622178896a</id>
      <masked>false</masked>
      <name>first_name</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.middle_name</defaultValue>
      <description></description>
      <id>6fadcdb0-97c7-467d-bd9f-05b52b15244e</id>
      <masked>false</masked>
      <name>middle_name</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.last_name</defaultValue>
      <description></description>
      <id>1143374a-b38e-440d-8d5a-4df70f890657</id>
      <masked>false</masked>
      <name>last_name</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.email</defaultValue>
      <description></description>
      <id>36ccdd7e-7ed9-4c35-8dc7-ff98ee76dcbc</id>
      <masked>false</masked>
      <name>email</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.address1</defaultValue>
      <description></description>
      <id>1f9b5903-49ef-4342-8334-4d8d8e10095a</id>
      <masked>false</masked>
      <name>address1</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.city</defaultValue>
      <description></description>
      <id>68041e3b-d8b9-4b29-bf7e-7c9ff02b3b3e</id>
      <masked>false</masked>
      <name>city</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.state</defaultValue>
      <description></description>
      <id>9cee0ce2-4ff8-42be-82f4-f2b322e9beef</id>
      <masked>false</masked>
      <name>state</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.country</defaultValue>
      <description></description>
      <id>f324f94f-4de5-45d8-836f-7a49bddae0df</id>
      <masked>false</masked>
      <name>country</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.birth_date</defaultValue>
      <description></description>
      <id>0decfc6a-706e-42fc-a624-9bedd83c8fe1</id>
      <masked>false</masked>
      <name>birth_date</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.ssn</defaultValue>
      <description></description>
      <id>b47de1a8-815a-4d67-80aa-e8be150e8580</id>
      <masked>false</masked>
      <name>ssn</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.id_card_number</defaultValue>
      <description></description>
      <id>5ed40c83-30c7-4075-bcca-09b8b3001816</id>
      <masked>false</masked>
      <name>id_card_number</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.id_card_expiration_date</defaultValue>
      <description></description>
      <id>91823223-da45-4b89-8277-f51eee9635cb</id>
      <masked>false</masked>
      <name>id_card_expiration_date</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.nationality</defaultValue>
      <description></description>
      <id>4aacb8b1-a3b7-47b1-9a11-b865bd7340df</id>
      <masked>false</masked>
      <name>nationality</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.company</defaultValue>
      <description></description>
      <id>b88993c7-a9bb-4ae6-9408-1b67dc348cdc</id>
      <masked>false</masked>
      <name>company</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.postal_code</defaultValue>
      <description></description>
      <id>eada8153-e1c4-4c5d-87d9-97756d531950</id>
      <masked>false</masked>
      <name>postal_code</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
