<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>list users</name>
   <tag></tag>
   <elementGuidId>6a4f0c12-6b17-4076-82b2-e05a219ab581</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic NmI4MGEzODMtNTZhYi00ZjRkLWFkYzItYTk1ZDFiNzVlODgxOjZlMGUzMTQ3LTljZWEtNDIwNS1hOWUzLTUyMDBiZGZjMTM4Zg==</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>https://${url}/users?count=${count}&amp;start_index=${start_index}&amp;sort_by=${sort_by}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.url</defaultValue>
      <description></description>
      <id>b2a1bb0e-508a-46c2-bbfd-d53667c86880</id>
      <masked>false</masked>
      <name>url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.count</defaultValue>
      <description></description>
      <id>5d88a520-2831-44c3-8e11-5045ee9144d4</id>
      <masked>false</masked>
      <name>count</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.start_index</defaultValue>
      <description></description>
      <id>51aa1a63-29b8-4dc4-b5e6-999a7c81d568</id>
      <masked>false</masked>
      <name>start_index</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.sort_by</defaultValue>
      <description></description>
      <id>f36cc503-8ff1-4055-869d-6715b706a9eb</id>
      <masked>false</masked>
      <name>sort_by</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
